artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1TlOwWTjQ3CuiClrDvGkVk_H4n2_ABKTu/view?usp=sharing
  local_data_file: artifacts/data_ingestion/raw_data.zip
  unzip_dir: artifacts/data_ingestion/raw
  ingested_train_dir: artifacts/data_ingestion/ingested_train_dir
  ingested_test_dir: artifacts/data_ingestion/ingested_test_dir
  train_file_name: Train.csv
  test_file_name: Test.csv



data_validation_config:
  schema_dir: configs
  schema_file_name: schema.yaml
  validated_dir: artifacts/data_validation
  validated_train_dir: artifacts/data_validation/validated_train
  validated_test_dir: artifacts/data_validation/validated_test


data_transformation_config:
  transformed_dir: artifacts/transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  transformed_train_file_name: Train.npz
  transformed_test_file_name: Test.npz

  preprocessing_dir: artifacts/preprocessed
  preprocessed_object_file_name: preprocessed.pkl

  
model_trainer_config:
  trained_model_dir: artifacts/trained_model
  model_file_name: model.pkl
  model_report_file_name: model_report.json
  base_accuracy: 0.5
  model_config_dir: configs
  model_config_file_name: model.yaml


model_evaluation_config:
  model_evaluation_file_name: artifacts/model_evaluation/model_evaluation.yaml
  best_model: best_model
  

model_pusher_config:
  model_export_dir: prediction_service/model.pkl
